
<!-- <p style="color:#7489fe;font-size:60%; text-align: center">Copyright 2014/2015 Imagine K12</p>' -->
<script type="text/javascript">

</script>
<p class="angelfooter"><Copyright> &copy; Copyright 2016/2017 Geoff Ralston</Copyright> --
    <a href="javascript:void(0);"
       NAME="Privacy"  title=" Angelcalc Privacy "
       onClick=window.open("/static/privacy.html","Privacy","width=700,height=400,0,status=0,scrollbars=1");>Privacy</a> --
    <a href="javascript:void(0);"
       NAME="TOS"  title=" Angelcalc Terms of Service "
       onClick=window.open("/static/tos.html","TOS","width=700,height=400,0,status=0,");>Terms</a></p>
