

    <div style="margin: 0px 0px 0px 0px; height:500px; width:75%; overflow-y:none">
    Angelcalc is intended to be used to manage an individual's investments in private companies. These investments
    are typically called "angel"
    investments and vary largely in size and deal terms. Angelcalc has built in most standard terms,
    but you can really use it for any
    investment. Most of us angels have typically managed our deals with spreadsheets,
    but over time these tend to get ugly and painful to use. Angelcalc is purpose built just
    for those investments.
    <p/>
    The major functions which exist today are outlined below. However, if, at any time you would like to
    begin, simply click below: (or on the ANGELCALC logo on the top left, or equivalently on the
    <span style="color:blue">Home</span> link
    on the top right).  You can always come back here by clicking on the <span style="color:blue">Help</span>
    link in the top right of the page.
    <p/>
    <a href="/investments">Go to the Investments Start Page</a>.
    <p></p> <hr><p></p>
    <h2>Angelcalc Functions</h2>
    <div style="margin: 0px 0px 0px 30px">
    <p></p>
    <ol>
        <li style="color:blue">Investments</li>
        The standard and default view for Angelcalc is a table of your investments which includes the name of the company
        in which you invested, the date of the investment, the round in which you invested, the amount of money
        invested, the number of shares you received (if any) as part of the investment, and any notes you
        wish to add.
        <p></p>
        an investment in a convertible instrument (a SAFE or a note) may be converted to equity by clicking on
        the linked <span style="color:blue">SAFE</span> or <span style="color:blue">Note</span> in the Round
        column.
        <p></p>
        This view is <span style="font-weight:bold">sortable</span> by any of its columns and the small arrows next to each company name allow you to edit
        the investment, delete the investment, or specify an exit for the company.
        <p />

        A <span style="font-weight:bold">new investment</span> may be created by clicking on the "+" sign in the left hand navigation bar next to the
        "Investments" link.
        <p/>
        Companies in which you have invested are categorized in to different statuses:

        <table style="padding:0px; border-spacing: 10px; width: 75%">
            <tr><td style="vertical-align:top;">Active</td><td>Companies still alive and operating.</td></tr>
            <tr><td style="vertical-align:top;">Acquired</td><td>Companies which have been acquired and no longer operate independently.</td></tr>
            <tr><td style="vertical-align:top;">IPO</td><td>Companies which have sold equity on public markets and are still alive and operating.</td></tr>
            <tr><td style="vertical-align:top;">Dead</td><td>Companies which failed. (There is, of course, some ambiguity between companies which
                         which acquired or acqui-hired at a very low price). It is up to you to decide how you
                want to categorize them.</td></tr>
        </table>
        The Investments view may be limited to any one of these categories by clicking on the appropriate link
        under the <span style="color:green">Filter</span> section of the left hand navigation bar.
        <p></p>
        <li style="color:blue">Distributions</li>
        You may get to the Distributions view by clicking the link in the left hand nav bar. Distributions occur when
        a company exits (or potentially returns capital to investors for other reasons). This table again includes the
        company name, the date of the distribution, the type of distribution (cash or stock), the amount of the
        distribution, and finally any notes you want to add. This table is also sortable by any of the columns.
        <p/>
        Similarly to Investments, a new distribution may be added by clicking on the "+" link to the right of
        the link in the left hand nav and the view may be filtered by clicking on a link in the
        <span style="color:green">Filter</span> section.

        <li style="color:blue">Companies</li>
        The Companies view gives a company centric view of all of your investments.
        <p/>
        Angelcalc has a number of startup companies already in its database. However, if you invest in a company which
        is not in the database you may enter it when you add the investment, or directly by clicking on the
        "+" sign next to the Companies link in the left hand nav. This creates a new company but does not create a new
        investment in your portfolio.
        <p/>
        You have a personal set of notes associated with each company which you may enter by clicking on a
        company name and then on <span style="color:blue">Add a new note</span>. You may also add more information
        about each company, including company founders, by clicking on the <span style="color:blue">edit company</span>
        link in the left hand portion of the company notes page.

        <li style="color:blue">Portfolio</li>
        The Portfolio Value view allows you to easily keep track of the value of your active portfolio. However, in
        order to do this you must know how many shares of stock you own, the number of shares of fully diluted
        stock the company has outstanding, and the most recent value of the company.
        <p/>
        Generally, you will only know the first of these if you have invested in an equity round or a convertible
        which has converted. If not, Angelcalc makes no effort to value the investment.
        The last two values you must get by asking the company. Some companies may be reticent to give out
        the information, but you have a right as an investor to understand how much of the company you own,
        so be firm!
        <p/>
        It is slightly awkward to enter these numbers currently (any advice?). For now, you must click on a
        company name to get to its Notes page. Then add a note of type "Valuation Update". You may add as many as
        you like and the most recent will be used in the Portfolio Value view.

        <li style="color:blue">Conversions</li>
        As noted above, from the Investments view an investment in a convertible instrument (a SAFE or a note) may be converted to equity by clicking on
        the linked <span style="color:blue">SAFE</span> or <span style="color:blue">Note</span> in the Round
        column. Angelcalc has extensive modeling abilities in order to help you predict your future ownership
        after your SAFE or Note converts. To start modeling click on the "Model Conversions" or "Compare Conversions"
        link in the left hand nav.
        <p/>
        To learn more click <a href="/investments?help=model">here</a>.
        <p />
        <li style="color:blue">Import/Export</li>
        Most of us have kept track of our investments and returns via a spreadsheet. Angelcalc can import those
        entries via a comma separated value (CSV) file which nearly all spreadsheets can export. If you click on the
        "Import" link in the left hand nav you will be given the format of a file for investments, and a different
        file for distribution.
        <p/>
        Similarly, Angelcalc can export its investment and distribution information to a CSV file for use with
        a spreadsheet. Just click on the "Export" link in the left hand nav.
        <li style="color:blue">Tax</li>
        Angelcalc allows you to create a simple report for tax preparation. The format is a CSV file with all
        of your returns for the year and a list of all relevant investments. Clicking on the "Tax" left hand nav link
        will show you the format and allow you to choose the quarter or year for the report.
        <p/>
        One of the more complex aspects of tax reporting for angel investing is keeping track of the basis
        used from one or more investments on one or more distributions. Angelcalc allows you to enter and track
        this when
        you create a distribution or later by editing the distribution.
        <li style="color:blue">Analysis</li>
        To be honest, there is almost nothing here. You can see a summary of the number of companies in which you have
        invested, how many total investments you have made, how much you have invested, the returns you have from
        those investments, and your active portfolio value in the left had nav Summary. There are also a
        couple of graphs. So what would you like?

    </ol>
    </div>

    <p></p> <hr><p></p>

    <span style="color: red">Disclaimer</span><br />
    The values calculated by Angelcalc are not guaranteed to be accurate by the
    author. It is likely that there will always be differences based on different assumptions
    or different inputs to different calculations.
    </span>


    </div>
