<?php
/**
 * Created by PhpStorm.
 * User: geoff
 * Date: 6/2/14
 * Time: 1:13 PM
 */
require_once "angelObjDB.inc";
require_once "angelview.inc";

require_once "angelObjlogfile.inc";
require_once "angelObjPerson.inc";
require_once "angelObjCompany.inc";
require_once "angelObjInvest.inc";
require_once "angelObjPayout.inc";
require_once "angelObjNote.inc";
require_once "angelObjNews.inc";
require_once "angelObjTracker.inc";

require_once "angelObjFund.inc";
require_once "angelObjFundCFModel.inc";
require_once "angelObjFundInvest.inc";
require_once "angelObjFundNote.inc";

require_once "angelObjConvert.inc";
require_once "angelObjModel.inc";
require_once "angelObjBasis.inc";
require_once "angelObjNewEntry.inc";

?>
