<div id="faqDiv">
    <ul>
        <li>why don't notes include interest and how do i handle that?
        </li>
        <li>what do i do if my convertible isn't here?

        </li>
        <li>what if i don't know some of this information?

        </li>
        <li>what is "shares outstanding again"?

        </li>
        <li>why isn't the number of shares i got the same?

        </li>
        <li>how come sometimes i get preferred and common shares?  does it matter?

        </li>
        <li>where can i find the text of the y combinator safe?

        </li>
        <li>what is the difference between the pre options and the post options

        </li>
        <li>what is the difference between a pre money and a post money valuation.

        </li>
        <li>why do some convertibles have a discount and a cap?

        </li>
        <li>how does a discount and a cap interact.

        </li>

    </ul>

</div>
