

    <p></p>

    Angelcalc models the conversion of safes and/or convertible notes during an equity financing. It uses
    techniques similar to those used by Microsoft Excel to make its calculations. You may create multiple
    models of equity rounds with conversions. To get started <a href="/model?new">create a new model</a>.
    <p></p>
    <span style="color: red">Disclaimer</span><br />
    The values calculated by this model are for comparison purposes only. Their accuracy is not guaranteed by the
    author. It is likely that this model will differ from Excel models of the same capitalization table, even when
    the inputs are identical due to rounding errors. No representation is made in any way as to which is the "correct"
    model in this case.
    </span>

