
<div id="header">
    <table border=0 cellpadding=0 cellspacing=0 width=100% height='30px' width='200px' class="angelcalcTopNav">
    <tr><td align=left><a href="index">
                <?php
                $logo = $GLOBALS["logo"];
                echo "<img height='30px' width='200px' src=$logo></a></td>";
                ?>

        <td align=center valign=middle width=10%><br><br><br></td>
        <td> </td>
    </tr></table></div><div id=all style="margin:20px;padding-top:10px;">